todo_backend/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin
from accounts import views as accounts_views

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/',include('accounts.urls')),
    url(r'^todos/',include('todos.urls')),
    url(r'^$',accounts_views.home,name="home")
]

#   DEBUG TOOLBAR SETTINGS
if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

todos/urls.py
from django.conf.urls import url
from . import views
from todos.views import TodosView

#   If multiple url.py files exist, app_name allows you specify in TEMPLATES which url file you want to use
app_name = 'todos'

urlpatterns = [
    url(r'^list_todos/',views.list_todos,name='list_todos'),
    url(r'^create_todo/',views.create_todo,name='create_todo'),
    url(r'^edit_todo/(?P<pk>[0-9]+)/',views.edit_todo,name='edit_todo'),
    url(r'^delete_todo/(?P<pk>[0-9]+)/',views.delete_todo,name='delete_todo'),

    #   URLS FOR REST API CLASS BASED VIEW
    url(r'^api/$', TodosView.as_view(), name="list_todos_api"),
    url(r'^api/(?P<pk>[0-9]+)/$', TodosView.as_view(), name="update_todos_api"),
]

todos/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django.conf import settings    #   For accessing the default user model

class Todo(models.Model):
    STATUS_TYPES = (
        ('Todo', 'Todo'),
        ('Doing', 'Doing'),
        ('Done', 'Done'),
    )
    #   There exists a One-To-Many relationship between User and Todo
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
    )

    title = models.CharField(
        max_length = 30
    )
    description = models.CharField(
        max_length = 200,
    )
    status = models.CharField(
        max_length = 10,
        choices = STATUS_TYPES,
        default = 'Todo'
    )

    def __unicode__(self):
        return self.title

todos/forms.py
from django import forms
from .models import Todo


class TodoForm(forms.ModelForm):

    #   constructor
    def __init__(self,user,*args,**kwargs):
        #   assign passed in user locally
        self.user = user
        super(TodoForm,self).__init__(*args,**kwargs)


    #   what happens when the form is saved
    def save(self,commit=True):
        #   prevent the form from saving immediately
        #   need to first assign the user to the object
        #   before saving to the DB
        instance = super(TodoForm,self).save(commit=False)

        #   auto set the user instance to that provided by the view
        instance.user = self.user

        if commit:
            instance.save()
        return instance

    #   Define which model elements to display in the form
    class Meta:
        model = Todo
        fields = ('title',
                  'description',
                  'status',)

todos/views.py
from __future__ import unicode_literals

from django.core.urlresolvers import reverse
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from .forms import TodoForm
from .models import Todo

#   For use with REST
from rest_framework.response import Response
from rest_framework.views import APIView
from rest_framework import status
from todos.serializer import TodoSerializer
from todos.models import Todo
from django.core.paginator import Paginator

import logging
logger = logging.getLogger(__name__)


@login_required()
def list_todos(request):

    #   Try to retrieve the list of Todos for the current user
    try:
        todo_list = Todo.objects.filter(user_id=request.user.id)
    except:
        todo_list = {}

    '''
        if NOT POST:
        Create a reference to the form and pass as an argument
        to the template
    '''
    if request.method != 'POST':
        form =  TodoForm(request.user)

    return render(request,'todos/list_todos.html',{'form':form,'todo_list':todo_list,'username':request.user.username,'user_id':request.user.id})


@login_required()
def create_todo(request):
    """
    -   Need to create a FORM in forms.py
    -   Assign current user to the todo object
    -   Save the Todo
    -   Forward the user back to the todo list
    """
    #   If the form has been posted
    if request.method == 'POST':
        form = TodoForm(request.user,request.POST)

        #   If the form is valid then save it
        if form.is_valid():
            #   the currently logged in user is associated with
            #   the Todo item
            form.save()
            return redirect(reverse('todos:list_todos'))
        else:
            messages.error(request,'There was an issue and Todo item did not save')

    #   refresh the list of todos
    return redirect(reverse('todos:list_todos'))


@login_required()
def edit_todo(request,pk):
    '''
    -   Retrieve the Todo item if POST is the method to get to this function
    -   Pass it to the template 'list-todo'
    -   Use If/Else in the template to populate the form if object was passed
    '''
    if request.method == 'POST':
        todo = Todo.objects.get(id=pk)

        status = 'All'

        #   If STATUS IS DONE -REMOVE
        #   DELETE
        #   ELSE
        #   SAVE THE FORM
        if request.POST['status'] is not None:
            if request.POST['status'] != 'All':
                status = request.POST['status']

        logger.debug('STATUS IS '+status)

        if('Done-Remove'==status):
            logger.debug('NEEDS TO BE REMOVED')
            todo.delete()
            return redirect(reverse('todos:list_todos'))
        else:
            form = TodoForm(request.user, request.POST,instance=todo)
            if form.is_valid():
                form.save()
                #return render(request, 'todos/list_todos.html', {'form':form})
                return redirect(reverse('todos:list_todos'))
    else:
        return redirect(reverse('todos:list_todos'))


@login_required()
def delete_todo(request,pk):
    #   ensure that the request came from the dislike form in the template
    if request.method == 'POST':
        todo = Todo.objects.get(id=pk)
        todo.delete()

    return redirect(reverse('todos:list_todos'))


"""
Class Based View to handle incoming API requests relating to 'todo' items
"""
class TodosView(APIView):
    def get(self,request,pk=None):
        """
        Handles GET requests
        -   IF no primary key is contained in the URL
            -   Check for status, user_id and page and filter for them
            OR
            -   Retrieve a complete list of 'todo' items from the Todo model,
            -   serialize them using the TodoSerializer to JSON and return the serialized todo items
        -   ELSE if a primary key was supplied
            -   Only retrieve the instance for the relevant record based on the primary key
        """
        user_id = 0
        status = 'All'
        page = 'All'
        recordsPerPage = 5

        logger.debug('API GET REQUEST MADE')

        if pk is None:
            #   RETRIEVE THE PARAMETERS PASSED IN
            #   check the status from the request
            if self.request.GET['status'] is not None:
                if self.request.GET['status'] != 'All':
                    status = self.request.GET['status']

            #   check the user from the request
            if self.request.GET['user_id'] is not None:
                if self.request.GET['user_id'] != 0:
                    user_id = self.request.GET['user_id']

            #   check the user from the request
            if self.request.GET['page'] is not None:
                if self.request.GET['page'] != 'All':
                    page = self.request.GET['page']

            logger.debug('status is '+status)
            logger.debug('user_id '+user_id)
            logger.debug('page '+page)

            #########   FILTERS FOR EACH PARAM SCENARIO   ############
            if user_id != 0 and status == 'All':
                todo_items = Todo.objects.filter(user_id=user_id)
            elif user_id != 0 and status != 'All':
                todo_items = Todo.objects.filter(user_id=user_id,status=status)
            else:
                todo_items = Todo.objects.all()

            #   User the Paginator to retrieve pages of records before serializing the data
            if page != 'All':
                paginator = Paginator(todo_items,recordsPerPage)
                num_pages = paginator.num_pages
                count = paginator.count
                todo_items = paginator.page(int(page))
                serializer = TodoSerializer(todo_items, many=True,num_pages=num_pages,count=count)
            else:
                serializer = TodoSerializer(todo_items,many=True)

            #   use a variable to store the serialized data
            serialized_data = serializer.data
            return Response(serialized_data)
        else:
            todo= Todo.objects.get(id=pk)
            serializer = TodoSerializer(todo)
            serialized_data = serializer.data
            return Response(serialized_data)

    def post(self,request):

        """
        Handles POST requests
        This view takes the 'data' property from the 'request' object,
        deserializes it into a 'Todo' object and stores it in the DB

        Returns a 201(successfully created) if the item is successfully created,
        otherwise returns a 400 (bad request)
        """
        serializer = TodoSerializer(data=request.data)

        """
        -   Check if valid
            -   if not
                -   a bad request response is returned
            -   else
                -   save the data and return the data a success status
        """
        if not serializer.is_valid():
            return Response(serializer.errors,
                            status=status.HTTP_400_BAD_REQUEST)
        else:
            serializer.save()
            return Response(serializer.data,
                            status=status.HTTP_201_CREATED)

    def put(self,request,pk):
        """
        Handle PUT requests
        -   Retrieve a Todo instance based on primary key from URL
        -   Take the data property from the 'request' object
            -   Update the relevant 'todo' instance
        -   Check to see if the data in the request is valid
            -   If not:
                -   a 400 (bad request) is returned
            -   else
                -   save and returns the updated object data
        """
        todo = Todo.objects.get(id=pk)
        serializer = TodoSerializer(todo,data=request.data)

        if not serializer.is_valid():
            return Response(serializer.errors,
                            status=status.HTTP_400_BAD_REQUEST)
        else:
            serializer.save()
            return Response(serializer.data)

    def delete(self,request,pk):
        """
        Handle DELETE requests to the API

        Retrieves a 'todo' instance based on the primary key passed in the URL
        and then deletes the relevant instance

        Returns a 204 (no content) status to indicate that the item was deleted
        """
        todo = Todo.objects.get(id=pk)
        todo.delete()
        return Response(status=status.HTTP_204_NO_CONTENT)

todos/templates/todos/list_todos.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load bootstrap_tags %}
{% block content %}
    {% if message %}
        {{ message }}
    {% endif %}
    <div class="container contents">
        <div class="row">
            <div class="col-sm-3">&nbsp;</div>
            <div class="col-sm-6 centered title">
                <h1>Todo's for {{ username|title}}</h1>
            </div>
            <div class="col-sm-3">
                &nbsp;
            </div>
        </div>
        <div id="pagination" class="row">
            <div class="col-sm-3"><button id="create-todo-btn" type="button" class="btn btn-primary btn-large btn-block" data-toggle="modal" data-target="#todo-modal">Create Todo<span id="user_id" hidden>{{ user_id }}</span></button></div>
            <div class="col-sm-6 centered"><p>Page: <span id="page_links"></span><br><span id="record_count"></span></p></div>
            <div class="col-sm-3">
                <p>
                    Sort by Status:&nbsp;
                    <select id="choose_status" class="select-menu">
                        <option value="All">All</option>
                        <option value="Todo">Todo</option>
                        <option value="Doing">Doing</option>
                        <option value="Done">Done</option>
                    </select>
                </p></div>
        </div>
        <div class="row">
            <div id="REST-data" class="col-sm-12" ></div>
        </div>
        <div class="modal fade" id="todo-modal" tabindex="-1" role="dialog" aria-labelledby="todo-form-modal" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h4 class="modal-title" id="todo-form-header">Todo Item</h4>
                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    </div>
                    <div class="modal-body">
                        <form name="todoForm" id="todoForm" role="form" method="post" action="{% url 'todos:create_todo' %}" class="account-form" enctype="multipart/form-data">
                            {% csrf_token %}
                            {% if form %}
                                {{ form | as_bootstrap }}
                            {% endif %}
                            <div class="modal-footer">
                                <button type="button" id="close-btn" class="btn btn-default" data-dismiss="modal">Close</button>
                                <button type="submit" id="submit-btn" class="btn btn-primary">Create</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
        <div class="modal fade" id="edit-todo-modal" tabindex="-1" role="dialog" aria-labelledby="todo-form-modal" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h4 class="modal-title" id="edit-todo-form-header">Edit Todo Item</h4>
                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    </div>
                    <div class="modal-body">
                        <form name="editTodoForm" id="editTodoForm" role="form" class="account-form" enctype="multipart/form-data">
                            {% csrf_token %}
                            <div class="form-group">
                                <label>Title</label>
                                <input type="text" id="edit_title" name="edit_title" class="form-control" required>
                            </div>
                            <div class="form-group">
                                <label>Description</label>
                                <input type="text" id="edit_description" name="edit_description" class="form-control" required>
                            </div>
                            <div class="form-group">
                                <label>Status</label>
                                <select class="form-control" id="edit_status" name="edit_status" >
                                    <option value="Todo" selected>Todo</option>
                                    <option value="Doing">Doing</option>
                                    <option value="Done">Done</option>
                                </select>
                            </div>
                            <div>
                                <input id="edit_todo_id" type="hidden" value="">
                            </div>
                            <div class="modal-footer">
                                <button type="button" id="close-edit-btn" class="btn btn-default" data-dismiss="modal">Close</button>
                                <button type="submit" id="submit-edit-btn" class="btn btn-primary">Update</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}
{% block script %}
    <script src="{% static 'js/globals.js' %}"></script>
    <script src="{% static 'js/talk_to_api.js' %}"></script>
    <script src="{% static 'js/list_todos.js' %}"></script>
{% endblock %}